<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
   <key>scopeName</key><string>source.blt</string>
   <key>fileTypes</key><array><string>blt</string></array>
   <key>foldingStartMarker</key><string>\{\s*$</string>
   <key>foldingStopMarker</key><string>^\s*\}</string>
   <key>patterns</key><array>
      <dict>
         <key>name</key><string>meta.blt-commands</string>
         <key>begin</key><string>`</string>
         <key>end</key><string>`</string>
         <key>captures</key><dict>
            <key>0</key><dict>
               <key>name</key><string>punctuation.section.embedded.blt-commands</string>
            </dict>
         </dict>
         <key>patterns</key><array>
            <dict>
               <key>include</key><string>#meta_blt_commands</string>
            </dict>
         </array>
      </dict>
      <dict>
         <key>name</key><string>string.other</string>
         <key>match</key><string>[^`]+</string>
      </dict>
   </array>
   <key>repository</key><dict>
      <key>meta_blt_commands</key><dict>
         <key>patterns</key><array>
            <dict>
               <key>name</key><string>source.lua</string>
               <key>begin</key><string>!</string>
               <key>end</key><string>!</string>
               <key>patterns</key>
               <array>
                  <dict>
                     <key>include</key>
                     <string>source.lua</string>
                  </dict>
               </array>
            </dict>
            <dict>
               <key>name</key><string>keyword.operator.symbolic.untitled</string>
               <key>match</key><string>\b([;{}()\[\],\?:\+\*#^%\-]|\.\.?|//?|&gt;[&gt;=]?|&lt;[&lt;=]?|~=?|==?|&amp;&amp;?|\|\|?)\b</string>
            </dict>
            <dict>
               <key>name</key><string>keyword.operator.textual.logical</string>
               <key>match</key><string>\b(and|or|not)\b</string>
            </dict>
            <dict>
               <key>name</key><string>keyword.control.untitled</string>
               <key>match</key><string>\b(if|else|while|for|with|choose|break|continue|until)\b</string>
            </dict>
            <dict>
               <key>name</key><string>support.variable.untitled</string>
               <key>match</key><string>\b(__blt__|__ctx__|__k__)\b</string>
            </dict>
            <dict>
               <key>name</key><string>support.constant.untitled</string>
               <key>match</key><string>\b(nl)\b</string>
            </dict>
            <dict>
               <key>name</key><string>support.function.untitled</string>
               <key>match</key><string>\b(pgsub|explode|pad|rpad|lpad)\b</string>
            </dict>
            <dict>
               <key>name</key><string>constant.language.boolean</string>
               <key>match</key><string>\b(true|false)\b</string>
            </dict>
            <dict>
               <key>name</key><string>constant.language.nil</string>
               <key>match</key><string>\bnil\b</string>
            </dict>
            <dict>
               <key>name</key><string>storage.modifier.with-modifier</string>
               <key>match</key><string>\b(each|using)\b</string>
            </dict>
            <dict>
               <key>name</key><string>string.quoted.double.untitled</string>
               <key>begin</key><string>"</string>
               <key>end</key><string>"</string>
               <key>patterns</key><array>
                  <dict>
                     <key>name</key><string>constant.character.escape.decimal</string>
                     <key>match</key><string>\\\d{1,3}</string>
                  </dict>
                  <dict>
                     <key>name</key><string>constant.character.escape.hex</string>
                     <key>match</key><string>\\x[0-9a-fA-F]{2}</string>
                  </dict>
                  <dict>
                     <key>name</key><string>constant.character.escape.unicode</string>
                     <key>match</key><string>\\u\{[0-9a-fA-F]+\}</string>
                  </dict>
                  <dict>
                     <key>name</key><string>constant.character.escape.untitled</string>
                     <key>match</key><string>\\.</string>
                  </dict>
               </array>
            </dict>
            <dict>
               <key>name</key><string>string.quoted.single.untitled</string>
               <key>begin</key><string>'</string>
               <key>end</key><string>'</string>
               <key>patterns</key><array>
                  <dict>
                     <key>name</key><string>constant.character.escape.decimal</string>
                     <key>match</key><string>\\\d{1,3}</string>
                  </dict>
                  <dict>
                     <key>name</key><string>constant.character.escape.hex</string>
                     <key>match</key><string>\\x[0-9a-fA-F]{2}</string>
                  </dict>
                  <dict>
                     <key>name</key><string>constant.character.escape.unicode</string>
                     <key>match</key><string>\\u\{[0-9a-fA-F]+\}</string>
                  </dict>
                  <dict>
                     <key>name</key><string>constant.character.escape.untitled</string>
                     <key>match</key><string>\\.</string>
                  </dict>
               </array>
            </dict>
            <dict>
               <key>name</key><string>constant.numeric.decimal</string>
               <key>match</key><string>\b(\d+(\.\d*)?|\.\d+)([Ee][+\-]?\d+)?\b</string>
            </dict>
            <dict>
               <key>name</key><string>constant.numeric.hex</string>
               <key>match</key><string>\b0[Xx]([0-9a-fA-F]+(\.[0-9a-fA-F]*)?|\.[0-9a-fA-F]+)([Pp][+\-]?\d+)?\b</string>
            </dict>
            <dict>
               <key>name</key><string>variable.other</string>
               <key>match</key><string>\b[A-Za-z_][A-Za-z_0-9]*\b</string>
            </dict>
            <dict>
               <key>name</key><string>keyword.language.scope</string>
               <key>match</key><string>\b\$+\b</string>
            </dict>
            <dict>
               <key>name</key><string>comment.line.double-dash</string>
               <key>match</key><string>--[^\r\n`]*</string>
            </dict>
         </array>
      </dict>
   </dict>
</dict>
</plist>
